# Generated by Django 5.2.8 on 2026-02-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendancerecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password_text',
            field=models.CharField(blank=True, help_text='Plain text password for admin reference (Security Risk)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
