# Generated by Django 5.2.8 on 2026-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_password_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.section'),
        ),
    ]
