# Generated by Django 5.2.8 on 2026-02-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_assigned_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.section'),
        ),
    ]
