# Generated by Django 5.2.8 on 2026-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='manager_remarks',
            field=models.TextField(blank=True, help_text='Notes added by a manager for absent students', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('MANAGER', 'Manager')], default='TEACHER', max_length=10),
        ),
    ]
